#!/usr/bin/env python
import os
import requests
import sys
from subprocess import call

if len(sys.argv) != 2:
	sys.exit("Invalid number of parameters")

if sys.argv[1] == "-update" or sys.argv[1] == "-u":
	script_path = os.path.realpath(__file__)
	new_file = requests.get('https://raw.githubusercontent.com/jovit/susy-test-runner/master/test-runner').text
	out_file = open(script_path, 'w+')
	out_file.write(new_file)
	sys.exit("Test Runner updated with success");

if not os.path.isfile(sys.argv[1]):
	sys.exit("File '" + sys.argv[1] + "' not found.")

file_name = sys.argv[1][:-2]
print "Received file is: ", file_name

if os.path.isfile(file_name):
	os.remove(file_name)

print "Compiling " + file_name + ".c to " + file_name 
os.system("gcc " + file_name + ".c -o " + file_name)

if not os.path.isfile(file_name): 
	sys.exit('\033[91m' + " Error during compilation" + '\033[0m');

	
lab_number = file_name[0].upper() +  file_name[1:]

inputs = []
expected_outputs = []
outputs = [];
outputs.append("");

print '\033[93mLOADING TESTS\033[0m'
for i in range(1,7):
	inputs.append(requests.get('https://susy.ic.unicamp.br:9999/mc102wy/'+lab_number+'/dados/arq0'+str(i)+'.in', verify=False).text)
	expected_outputs.append(requests.get('https://susy.ic.unicamp.br:9999/mc102wy/'+lab_number+'/dados/arq0'+str(i)+'.res', verify=False).text)


out_file = open('outfile', 'w+')
out_file.close()

failed = 0

for i in range(0,6):
	print  '\033[93m' + "------------------------------------------" + '\033[0m'
	print '\033[93m' + "-------------STARTING ("+str(i+1)+"/6)---------------" + '\033[0m'
	in_file = open('infile', 'w+')
	in_file.write(inputs[i])
	in_file.close()
	os.system("./"+file_name + " < infile" + " > outfile")

	out_file = open('outfile', 'r')
	output_resulted = out_file.read()
	out_file.close()

	if output_resulted == expected_outputs[i]:
		print "TEST "+str(i+1)+ '\033[92m' + " SUCCESS" + '\033[0m'
	else:
		failed += 1
		print "TEST "+str(i+1) + '\033[91m' + " FAILED" + '\033[0m'
		print "EXPECTED\n" + expected_outputs[i]
		print "FOUND\n" + output_resulted

print '\033[93m' + "------------------------------------------" + '\033[0m'
print "Tests finished running with success"
if failed == 0:
	print "All tests passed!. :D"
else:
	print str(failed), "tests out of 6 have failed. :-("

os.remove('infile')
os.remove('outfile')
os.remove(file_name)
	